apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherstation5-deployment
  labels:
    app: weatherstation5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherstation5
  template:
    metadata:
      labels:
        app: weatherstation5
    spec:
      containers:
      - name: weather-station
        image: omarkhairat/weather-station-seoncd-edition:latest
        ports:
        - containerPort: 8078
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092
        - name: CITY
          value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: weatherstation5-service
spec:
  type: NodePort
  selector:
    app: weatherStation5
  ports:
    - protocol: TCP
      port: 8078
      targetPort: 8078
