apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherstation1-deployment
  labels:
    app: weatherstation1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherstation1
  template:
    metadata:
      labels:
        app: weatherstation1
    spec:
      containers:
      - name: weather-station
        image: omarkhairat/weather-station-seoncd-edition:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092
        - name: CITY
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: weatherstation1-service
spec:
  type: NodePort
  selector:
    app: weatherStation1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
