apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherstation9-deployment
  labels:
    app: weatherstation9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherstation9
  template:
    metadata:
      labels:
        app: weatherstation9
    spec:
      containers:
      - name: weather-station
        image: omarkhairat/weather-station-seoncd-edition:latest
        ports:
        - containerPort: 8092
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092
        - name: CITY
          value: "9"
---
apiVersion: v1
kind: Service
metadata:
  name: weatherstation9-service
spec:
  type: NodePort
  selector:
    app: weatherStation9
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
