apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherstation7-deployment
  labels:
    app: weatherstation7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherstation7
  template:
    metadata:
      labels:
        app: weatherstation7
    spec:
      containers:
      - name: weather-station
        image: omarkhairat/weather-station-seoncd-edition:latest
        ports:
        - containerPort: 8090
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092
        - name: CITY
          value: "7"
---
apiVersion: v1
kind: Service
metadata:
  name: weatherstation7-service
spec:
  type: NodePort
  selector:
    app: weatherStation7
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
