apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherstation3-deployment
  labels:
    app: weatherstation3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherstation3
  template:
    metadata:
      labels:
        app: weatherstation3
    spec:
      containers:
      - name: weather-station
        image: omarkhairat/weather-station-seoncd-edition:latest
        ports:
        - containerPort: 8076
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092
        - name: CITY
          value: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: weatherstation3-service
spec:
  type: NodePort
  selector:
    app: weatherStation3
  ports:
    - protocol: TCP
      port: 8076
      targetPort: 8076
