apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherstation6-deployment
  labels:
    app: weatherstation6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherstation6
  template:
    metadata:
      labels:
        app: weatherstation6
    spec:
      containers:
      - name: weather-station
        image: omarkhairat/weather-station-seoncd-edition:latest
        ports:
        - containerPort: 8079
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092
        - name: CITY
          value: "6"
---
apiVersion: v1
kind: Service
metadata:
  name: weatherstation6-service
spec:
  type: NodePort
  selector:
    app: weatherStation6
  ports:
    - protocol: TCP
      port: 8079
      targetPort: 8079
