apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherstation2-deployment
  labels:
    app: weatherstation2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherstation2
  template:
    metadata:
      labels:
        app: weatherstation2
    spec:
      containers:
      - name: weather-station
        image: omarkhairat/weather-station-seoncd-edition:latest
        ports:
        - containerPort: 8075
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092
        - name: CITY
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: weatherstation2-service
spec:
  type: NodePort
  selector:
    app: weatherStation2
  ports:
    - protocol: TCP
      port: 8075
      targetPort: 8075
