apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherstation8-deployment
  labels:
    app: weatherstation8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherstation8
  template:
    metadata:
      labels:
        app: weatherstation8
    spec:
      containers:
      - name: weather-station
        image: omarkhairat/weather-station-seoncd-edition:latest
        ports:
        - containerPort: 8091
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092
        - name: CITY
          value: "8"
---
apiVersion: v1
kind: Service
metadata:
  name: weatherstation8-service
spec:
  type: NodePort
  selector:
    app: weatherStation8
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
